### ISSUE TITLE
I can't choose Nodejs 8.10 on AWS Lambda - directiveDiscovery Test failed

### ISSUE THREAD

**Issue by sidamo82** [alexa-samples/skill-sample-nodejs-smarthome-switch#16]
I can't choose nodejs 8.10 version on AWS. So, I try to choose Nodejs 12.x.

When I run "directiveDiscovery" test it closed with error:

2020-08-23T13:42:15.459Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token 'export'",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token 'export'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
        "    at Module.load (internal/modules/cjs/loader.js:986:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

**Comment by aszk** [comment]
I tried to reproduce the error but I failed to reproduce. Could you give me steps to reproduce and code if you change any code from the sample code? This might be related to your NodeJS configuration.

**Comment by dievaa** [comment]
Closing due to inactivity.
