### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by nutkracker** [alexa-samples/skill-sample-nodejs-smarthome-switch#2]
I've been following the tutorial, so far so good..
Now to test the Lambda function...  and I'm getting an error:

Syntax error in module 'index': SyntaxError
exports.handler = async function (event, context) {
^^^^^^^^
SyntaxError: Unexpected token function
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

Any ideas??

**Comment by nutkracker** [comment]
Upgraded Node to 8.10 (from 6.10) and this resolved the issue! :-)

**Comment by mikemaas-amazon** [comment]
You beat me to it. I tried the instructions again this morning and found that to be the issue. Also, I have a couple of small fixes to push in. There is one that will break the lambda. The log at https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/master/lambda/smarthome/index.js#L105 should be removed. I'll push a fix for that in the next few minutes.

**Comment by nutkracker** [comment]
Great thanks!
