### ISSUE TITLE
Import module aws/sdk error with Node 18

### ISSUE THREAD

**Issue by Lusquinhos** [alexa-samples/skill-sample-nodejs-smarthome-switch#20]
Hello,

I have the following error:

2023-08-15T18:18:53.309Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1029:21)",
        "    at async start (file:///var/runtime/index.mjs:1192:23)",
        "    at async file:///var/runtime/index.mjs:1198:1"
    ]
}

I am using Node v18

**Comment by Lusquinhos** [comment]
it's working after change Node version to 14. This issue can be closed Tahnk you!
