### ISSUE TITLE
uuid is not a function

### ISSUE THREAD

**Issue by guilhermelirio** [alexa-samples/skill-sample-nodejs-smarthome-switch#9]
Good afternoon. I followed the whole tutorial, but there is no way to select NodeJS 8.x anymore, only 10.x and 12.x.

Selecting 10.x or 12.x, the same error occurs:
`{
  "errorType": "TypeError",
  "errorMessage": "uuid is not a function",
  "trace": [
    "TypeError: uuid is not a function",
    "    at new AlexaResponse (/var/task/alexa/skills/smarthome/AlexaResponse.js:58:62)",
    "    at Runtime.exports.handler (/var/task/index.js:67:19)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}`

Logs:
`START RequestId: d7a4d7c7-48aa-425f-a00d-d15023a55eb1 Version: $LATEST
2020-03-08T15:42:29.039Z	d7a4d7c7-48aa-425f-a00d-d15023a55eb1	INFO	index.handler request  -----
2020-03-08T15:42:29.054Z	d7a4d7c7-48aa-425f-a00d-d15023a55eb1	INFO	{"directive":{"header":{"namespace":"Alexa.Discovery","name":"Discover","payloadVersion":"3","messageId":"1bd5d003-31b9-476f-ad03-71d471922820"},"payload":{"scope":{"type":"BearerToken","token":"access-token-from-skill"}}}}
2020-03-08T15:42:29.074Z	d7a4d7c7-48aa-425f-a00d-d15023a55eb1	INFO	index.handler context  -----
2020-03-08T15:42:29.074Z	d7a4d7c7-48aa-425f-a00d-d15023a55eb1	INFO	{"callbackWaitsForEmptyEventLoop":true,"functionVersion":"$LATEST","functionName":"skill-sample-nodejs-smarthome-switch","memoryLimitInMB":"128","logGroupName":"/aws/lambda/skill-sample-nodejs-smarthome-switch","logStreamName":"2020/03/08/[$LATEST]42601907f8394b98b95965e6a815575f","invokedFunctionArn":"arn:aws:lambda:us-east-1:534427607265:function:skill-sample-nodejs-smarthome-switch","awsRequestId":"d7a4d7c7-48aa-425f-a00d-d15023a55eb1"}
2020-03-08T15:42:29.075Z	d7a4d7c7-48aa-425f-a00d-d15023a55eb1	ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"uuid is not a function","stack":["TypeError: uuid is not a function","    at new AlexaResponse (/var/task/alexa/skills/smarthome/AlexaResponse.js:58:62)","    at Runtime.exports.handler (/var/task/index.js:67:19)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: d7a4d7c7-48aa-425f-a00d-d15023a55eb1
REPORT RequestId: d7a4d7c7-48aa-425f-a00d-d15023a55eb1	Duration: 78.50 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 87 MB	Init Duration: 345.32 ms	`

How to fix this error? 

Developing skill in pt-BR.

**Comment by guilhermelirio** [comment]
Fixed!

**Change line 16 of AlexaResponse.js:**
`let uuid = require('uuid');`

To:
`let uuid = require('uuid/v4');`

**Comment by DinisSkizee** [comment]
Change import to:
const { v4: uuidv4 } = require('uuid');

change call to:
uuidv4()
